name: iGetOP
main: org.iMCCode.iGetOP.iGetOP
version: 1.0
description: This plugin is made for the Server iGetOP!
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [We use totalfreedommod made by Madgeek1450, Prozza edited by iHess, MysteriAce, Falceso and the one and only kane_creeper05]

# Plugin.yml is no longer used to define commands.
# Due to the CommandPermissions, iGOP_Command, CommandParameters.
